name: Deploy Theme
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Yarn Install 
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install 
      - name: Build and deploy the theme
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: zip # will run `yarn build` command
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
