name: Deploy Theme
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '10.x'
      - run: yarn
      - name: Deploy Theme
        run: yarn zip 
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
